SET SERVEROUTPUT ON SIZE UNLIMITED
SET FEEDBACK ON

SELECT * FROM STORE_OWNER.STORE_PRODUCTS;
SELECT * FROM STORE_OWNER.STORE_PURCHASES;
SELECT * FROM STORE_OWNER.STORE_ORDERS;
SELECT * FROM STORE_OWNER.PRODUCT_PROFIT_PER_SALE;
SELECT * FROM STORE_OWNER.PRODUCT_OVERVIEW;


BEGIN

    STORE_OWNER.REPORTS_PACKAGE.GET_SALES_REP_QUARTERLY_SALES(2024);
    STORE_OWNER.REPORTS_PACKAGE.GET_QUARTERLY_MOST_SOLD_PRODUCTS(2024);
    STORE_OWNER.REPORTS_PACKAGE.GET_QUARTERLY_PURCHASES_REPORT(2024);
    STORE_OWNER.REPORTS_PACKAGE.GET_QUARTERLY_SALES_REPORT(2024);
    STORE_OWNER.REPORTS_PACKAGE.GET_TOP_CUSTOMERS_BY_QUARTER(2024);
    STORE_OWNER.REPORTS_PACKAGE.GET_PRODUCT_HISTORY_REPORT_PROCEDURE();

END;
/
